trigger:
  branches:
    include:
      - main

pool:
  name: 'Cualquiera'

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean install'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.11'
      publishJUnitResults: true
      testResultsFiles: '*/surefire-reports/TEST-.xml'
      sonarQubeRunAnalysis: false

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'C:\Agente\_work\1\s\target\gitlab.war'  # Especifica la ruta completa
      ArtifactName: 'java-app'